package de.hu_berlin.cchecker.ui.util.exceptions;

/**
 * An Exception that happens when a .trc file that is supposed to contain a TraceDataset can unexpectedly not be parsed.
 * 
 * @author Linus
 *
 */
public class InvalidTraceDatasetFileException extends Exception {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 3740208071585950418L;

	/**
	 * The file name of the file that could not be parsed to a TraceDataset.
	 */
	private final String fileName;
	
	/**
	 * Returns a new instance of InvalidTraceDatasetFileException with the given message and fileName.
	 */
	public InvalidTraceDatasetFileException(String message, String fileName) {
		super(message);
		this.fileName = fileName;
	}
	
	/**
	 * Returns the file name of the file that caused this exception.
	 */
	public String getFileName() {
		return this.fileName;
	}
}
