package de.hu_berlin.cchecker.ui.util.exceptions;

/**
 * An exception that happens when a launch shortcut is run with an invalid selection of files.
 * Normally, this is supposed to be prevented by the launch shortcut's enablement property,
 * but not all necessary validations can be made with that.
 * 
 * @author Linus
 *
 */
public class InvalidFileSelectionException extends Exception {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 2310847523199705550L;

	/**
	 * Returns a new instance of InvalidFileSelectionException with the given message.
	 */
	public InvalidFileSelectionException(String message) {
		super(message);
	}
}
