package de.hu_berlin.cchecker.ui.util.exceptions;

/**
 * An Exception that happens when a .pdfa or .dtmc file that is supposed to contain a 
 * {@link ProbabilisticAutomata} can unexpectedly not be parsed.
 * 
 * @author Linus
 *
 */
public class InvalidProbabilisticAutomatonFileException extends Exception {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = -2461069038558587757L;
	
	/**
	 * The file name of the file that could not be parsed to a ProbabilisticAutomata.
	 */
	private final String fileName;
	
	/**
	 * Returns a new instance of InvalidProbabilisticAutomatonFileException with the given message and fileName.
	 */
	public InvalidProbabilisticAutomatonFileException(String message, String fileName) {
		super(message);
		this.fileName = fileName;
	}
	
	/**
	 * Returns the file name of the file that caused this exception.
	 */
	public String getFileName() {
		return this.fileName;
	}
}
